### PR TITLE
Pp 1775 reverse commit for pull request 368

### PR DESCRIPTION
**Pull request by daniele-occhipinti**
## WHAT

The aim of this PR is to remove what has been added to master by pull request #368 ,
which is the change to start processing CAPTURE operation asynchronously
in the background.

We want to do so because we still need to do some work on it, but there is
new code on master that needs to be released.

This reverse commit has been produced by running this command:
`git revert -m 1 d01fe9e3be8bb4a1380c27e2e43bde1c9240f9a2`

### CODE REVIEW

**Comment by ghost** [comment]
There were no errors, go have a cup of coffee...

**Comment by ghost** [comment]
There were no errors, go have a cup of coffee...

**Comment by ghost** [comment]
There were no errors, go have a cup of coffee...

**Review by ckalista — APPROVED** [review]
LGTM!

**Pull request merged**
