### PR TITLE
PP-1377 As per ticket, the minimum length for bank card numbers is 12…

### PR DESCRIPTION
**Pull request by ijmad**
PP-1377 As per ticket, the minimum length for bank card numbers is 12, not 14.
This is correct in frontend but not in connector.
Fix connector to match.

### CODE REVIEW

**Comment by bazbremner** [comment]
I'd suggest that there's value in retaining a negative test for 12 digit card numbers, rather than just updating the extant postive tests from 12 to 14 digits, but otherwise it looks good.

**Comment by heathd** [comment]
Looks good. Would be nice to have a test that 12 digits are considered valid as well as considering 11 digits invalid (I **think** that's what @bazbremner was saying?)

**Comment by ijmad** [comment]
rebuild

**Comment by ijmad** [comment]
rebuild

**Pull request merged**
