### PR TITLE
PP-424 View detailed information on a specific payment via API

### PR DESCRIPTION
**Pull request by PauloPortugal**
- Adding a JSON Deserializer and JSON Serializer for the event
  timestamp

### CODE REVIEW

**Comment by davidillsley** [comment]
Did you consider using https://github.com/FasterXML/jackson-datatype-jsr310 ?

**Comment by PauloPortugal** [comment]
@davidillsley that was a gem :) ! Thanks for spotting it! I have made the same changes on the pay-publicapi 
https://github.com/alphagov/pay-publicapi/pull/44

**Comment by davidillsley** [comment]
rebuild

**Comment by PauloPortugal** [comment]
rebuild

**Comment by PauloPortugal** [comment]
rebuild

**Pull request merged**
