### PR TITLE
PP-280 following changes and improvements [might break E2E tests if self-service not changed accordingly so wait for Self-service 280 merge first]

### PR DESCRIPTION
**Pull request by rahul-vinayak**
- removed "updated" column from the listTransactions API, self-service should look at 'created_date' instead.
- CSV was showing the amount in the pence, fixed it to show in pounds
  now
- Connector public API for list transactions now returns amount in
  Pounds and not pence so that conversion happens at on place

### CODE REVIEW

**Comment by rahul-vinayak** [comment]
rebuild

**Comment by rahul-vinayak** [comment]
rebuild

**Comment by ckalista** [comment]
Code review done. Looks good to go.

**Comment by rahul-vinayak** [comment]
rebuild

**Comment by rahul-vinayak** [comment]
rebuild

**Pull request merged**
