### PR TITLE
PP-1777: Raise authorisation timeout errors to 20seconds

### PR DESCRIPTION
**Pull request by whpearson**
We were getting 20+ authorisation errors on a bad day due to
timeouts. Services have asked what was wrong.

This increases the timeout to 20 seconds to give the request more
time to complete.

### CODE REVIEW

**Comment by ghost** [comment]
There were errors, for info, please see...

**Comment by whpearson** [comment]
rebuild

**Comment by ghost** [comment]
There were errors, for info, please see...

**Comment by whpearson** [comment]
Rebuild

**Comment by ghost** [comment]
There were no errors, go have a cup of coffee...

**Review by SandorArpa — APPROVED** [review]
Discussed change

**Pull request merged**
