### PR TITLE
PP-863 Prepare connector to receive card_brand in authorisation payload request

### PR DESCRIPTION
**Pull request by ckalista**
## WHAT

This prepares the connector to receive the additional card_brand field in the payload of authorisation request so that the frontend changes can be merged subsequently.

### CODE REVIEW

**Comment by ckalista** [comment]
rebuild

**Comment by ckalista** [comment]
rebuild

**Comment by ckalista** [comment]
rebuild

**Comment by ckalista** [comment]
rebuild

**Comment by kakumara** [comment]
I assume there is no unit test for Card.java which needs alteration..
(Just seems odd that there's a change but no change to a test.. )

**Comment by ckalista** [comment]
rebuild

**Comment by ckalista** [comment]
rebuild

**Comment by kakumara** [comment]
👍

**Pull request merged**
