### PR TITLE
Run e2e inline

### PR DESCRIPTION
**Pull request by heathd**
Run end-to-end tests inline for connector builds

Pros:
- Test reports for e2e tests run on PRs are associated with the PR build
- test reports for connector master builds are associated with the master build

Cons:
- I can't think of any

### CODE REVIEW

**Comment by whpearson** [comment]
Is this worth putting into the jenkins library so it is easier to reuse?

**Comment by heathd** [comment]
@whpearson I'd rather prove it works reliably before abstracting it

**Review by alexbishop1 — APPROVED** [review]
Let’s give this a try

**Comment by heathd** [comment]
thanks!

**Pull request merged**
