### PR TITLE
PP-4637: Decryption ADR

### PR DESCRIPTION
**Pull request by oswaldquek**
@oswaldquek

### CODE REVIEW

**Review by alexbishop1 — CHANGES_REQUESTED** [review]
I’m possibly being a bit pernickety here but it feels like quite a lot of the decision is actually in the context part.

In the context bit, we could maybe start with a brief description of the two possible options (decrypting and not decrypting), noting what data we get with each and how the key/certificate requirements differ for each. The deal-breakers list (which is very good) could go either before or after this. Then the decision part could explain why not decrypting is best (in terms of the data we want being available and neither us nor our partner services having to mess with keys).

**Comment by oswaldquek** [comment]
@alexbishop1 Thanks for your input. I don't think you're being pernickety. I've never written an ADR before so your input is welcome, and in this case, I think valid.

**Comment by alexbishop1** [comment]
I’ve just corrected an error in my initial review! I said “decision” at the beginning of the second paragraph when I meant “context”! Sorry!

**Review by alexbishop1 — APPROVED** [review]
Awesome summary of the reasoning

**Pull request merged**
