### PR TITLE
PP-4293 Filter refunds by date range

### PR DESCRIPTION
**Pull request by simad**
## WHAT
- Adding filtering by date range to the new refunds search endpoint
- This PR is 1 of 2 prs, the next one will add validation and refactor the other endpoints

with @cobainc0

### CODE REVIEW

**Comment by mrlumbu** [comment]
Please can this be split up in to at least 2 PRs, one with the refactoring and one with the changes. I don't think all this needs to go in in one go, and it's pretty hard to review such a big change.

**Comment by simad** [comment]
@mrlumbu it certainly can be split. I didn't think a `+664 −370` change would've been considered hard to review, but 👍 will split in two PRs.

**Comment by simad** [comment]
@mrlumbu it certainly can be split. I didn't think a `+664 −370` change would've been considered hard to review, but 👍 will split in two PRs.

**Comment by simad** [comment]
@mrlumbu it certainly can be split. I didn't think a `+664 −370` change would've been considered hard to review, but 👍 will split in two PRs.

**Review by SandorArpa — APPROVED** [review]
LOKTM

**Pull request merged**
