### PR TITLE
PP-1582 Ignore unknown json properties from payment details

### PR DESCRIPTION
**Pull request by imranbohoran**
* As part of the 3DS work, we have to pass in the accept header
   and user agent header. To pass this from the frontend, we have to
   first let connector accept unknown properties.
 * This is temporary. Once frontend is passing the values, this code will be
   changed to remove the ignore and accept the specific headers.

with @alexbishop1

### CODE REVIEW

**Comment by imranbohoran** [comment]
rebuild

**Comment by imranbohoran** [comment]
rebuild

**Comment by imranbohoran** [comment]
rebuild

**Comment by rauligs** [comment]
👍

**Pull request merged**
