### PR TITLE
PP-572 Buf Fix - CSV displaying internal ChargeIds

### PR DESCRIPTION
**Pull request by rauligs**
```
* Test was asserting still internal ChargeId so changed and fixed.
```

### CODE REVIEW

**Comment by ckalista** [comment]
Code review done.

**Comment by rahul-vinayak** [comment]
You need to change the content length in the failing e2e test as the content has changed

**Comment by bazbremner** [comment]
rebuild

**Comment by rauligs** [comment]
rebuild

**Comment by PauloPortugal** [comment]
rebuild

**Pull request merged**
