### PR TITLE
PP-501 Database timezone alignment

### PR DESCRIPTION
**Pull request by rauligs**
## WHAT
- Charge events (and potentially other entities) used LocalDateTime with its respective converter to and from db entity. This wasn't consistent with the desired format of dates (already being used for Charges) as UTC ZoneDateTime.
- Despite this work was already done as part of another story related to Charge events, some clean up has been done such as removed _LocalDateTimeConverter_ which wasn't not being and shouldn't be used to convert to and from entities.
- Cleaned up Api paths constants to be consistent across the app, naming and location.
- Removed unused imports.
## HOW TO REVIEW
- Important piece is the removal of _LocalDateTimeConverter_,  the other bits are extras.
## WHO
- Any dev or web-ops

### CODE REVIEW

**Comment by rauligs** [comment]
rebuild

**Comment by imranbohoran** [comment]
Review done. Ready to merge when builds go green

**Comment by rauligs** [comment]
rebuild

**Comment by imranbohoran** [comment]
👍

**Pull request merged**
