### PR TITLE
PP-10675: replaced usage of set-output in run-pact-provider-tests.yml

### PR DESCRIPTION
**Pull request by Rkotyank**
Located and replaced all usages of set-output commands in our workflows.

### CODE REVIEW

**Review by katstevens — COMMENTED** [review]
The change looks ok here, but the Concourse tests need re-running before this PR can be merged. You can either rebase this PR to start everything all over again, or re-run the failed job in Concourse.

**Comment by Rkotyank** [comment]
> The change looks ok here, but the Concourse tests need re-running before this PR can be merged. You can either rebase this PR to start everything all over again, or re-run the failed job in Concourse.

Have re-run the concourse tests (1605), it seems to be working fine.

**Comment by katstevens** [comment]
> > The change looks ok here, but the Concourse tests need re-running before this PR can be merged. You can either rebase this PR to start everything all over again, or re-run the failed job in Concourse.
> 
> Have re-run the concourse tests (1605), it seems to be working fine.

I think you might need to re-trigger it with the same inputs (use the dotted circle on job 1604), otherwise it won't run the Concourse job against this PR.

**Comment by Rkotyank** [comment]
> > > The change looks ok here, but the Concourse tests need re-running before this PR can be merged. You can either rebase this PR to start everything all over again, or re-run the failed job in Concourse.
> > 
> > 
> > Have re-run the concourse tests (1605), it seems to be working fine.
> 
> I think you might need to re-trigger it with the same inputs (use the dotted circle on job 1604), otherwise it won't run the Concourse job against this PR.



> > > The change looks ok here, but the Concourse tests need re-running before this PR can be merged. You can either rebase this PR to start everything all over again, or re-run the failed job in Concourse.
> > 
> > 
> > Have re-run the concourse tests (1605), it seems to be working fine.
> 
> I think you might need to re-trigger it with the same inputs (use the dotted circle on job 1604), otherwise it won't run the Concourse job against this PR.

have re-run the concourse tests (1604.1), all good to go

**Review by katstevens — DISMISSED** [review]

**Comment by katstevens** [comment]
Hmm the `app-as-consumer pact verification` Concourse check never even got started, so we can't re-run it 🤔 We might have to rebase this PR against master after all I'm afraid.

**Review by katstevens — APPROVED** [review]

**Pull request merged**
