### PR TITLE
PP-172 Fix problem with wrongly initialized boolean

### PR DESCRIPTION
**Pull request by acceleanu**

### CODE REVIEW

**Comment by acceleanu** [comment]
rebuild

**Comment by acceleanu** [comment]
rebuild

**Comment by acceleanu** [comment]
rebuild

**Comment by ijmad** [comment]
rebuild

**Comment by ijmad** [comment]
rebuild

**Comment by ijmad** [comment]
rebuild

**Comment by ijmad** [comment]
rebuild

**Pull request merged**
