### PR TITLE
Jenkins hook setup

### PR DESCRIPTION
**Pull request by acceleanu**

### CODE REVIEW

**Comment by acceleanu** [comment]
run

**Comment by acceleanu** [comment]
run

**Comment by acceleanu** [comment]
run

**Comment by acceleanu** [comment]
run

**Comment by acceleanu** [comment]
run

**Comment by acceleanu** [comment]
run

**Comment by acceleanu** [comment]
run

**Comment by acceleanu** [comment]
run

**Comment by acceleanu** [comment]
run

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
run

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by ijmad** [comment]
rrun

**Comment by ijmad** [comment]
rrun

**Comment by ijmad** [comment]
rrun

**Comment by ijmad** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by ghost** [comment]
hello

**Comment by ijmad** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Comment by acceleanu** [comment]
rrun

**Pull request closed without merging**
